name: code
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  confirm_dialog: ^1.0.1
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.2.0
  http: any
  dio: ^5.1.2
  flutter_staggered_grid_view: ^0.6.2
  auto_size_text: ^3.0.0-nullsafety.0
  realm: any
  sqflite: ^2.2.8
  path_provider: ^2.0.15
  path: ^1.8.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  auto_route: ^7.2.0



dev_dependencies:
  auto_route_generator: ^7.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  intl: ^0.18.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/week2/Vector.png
    - assets/images/week2/bookYourRide.png
    - assets/images/week2/car.png
    - assets/images/week2/unitedStates1.png
    - assets/images/week2/image1.png
    - assets/images/biz_design/Ellipse_18.png
    - assets/images/biz_design/Ellipse_19.png
    - assets/images/biz_design/loading.png
    - assets/images/biz_design/n-Biz.png
    - assets/images/biz_design/Rectangle_5.jpg
    - assets/images/biz_design/image_41.png
    - assets/images/biz_design/image_1.png
    - assets/images/biz_design/image_12.png
    - assets/images/biz_design/image_11.png
    - assets/images/biz_design/bloc_image_1.png
    - assets/images/biz_design/bloc_image_2.png
    - assets/images/biz_design/bloc_image_3.png
    - assets/images/biz_design/bloc_image_4.png
    - assets/images/biz_design/bloc_image_5.png
    - assets/images/biz_design/bloc_image_6.png
    - assets/images/biz_design/bloc_image_7.png
    - assets/images/biz_design/bloc_image_8.png
    - assets/images/biz_design/bloc_image_9.png
    - assets/images/biz_design/image_13.png
    - assets/images/biz_design/image_14.png
    - assets/images/biz_design/image_15.png
    - assets/images/biz_design/image_40.png
    - assets/images/biz_design/Vector_1.png
    - assets/images/biz_design/background.png
    - assets/images/biz_design/Rectangle_12.png
    - assets/images/biz_design/Rectangle_28.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
    - family: Plus_Jakarta_Sans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-VariableFont_wght.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/icons/MyFlutterApp.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf

